apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: estafette-gcp-service-account
  labels:
{{ include "commonLabels" . | indent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
